---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: publish-index-image-task
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task to publish a built FBC index image using skopeo
  params:
    - name: sourceIndex
      type: string
      description: sourceIndex signing image
    - name: targetIndex
      type: string
      description: targetIndex signing image
    - name: retries
      type: string
      default: "0"
      description: Number of skopeo retries
    - name: publishingCredentials
      type: string
      default: "fbc-publishing-credentials"
      description: The credentials used to access the registries
    - name: requestUpdateTimeout
      type: string
      default: "360"
      description: Max seconds waiting for the status update
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  results:
    - name: requestMessage
  volumes:
    - name: publishing-credentials
      secret:
        secretName: $(params.publishingCredentials)
        defaultMode: 0444
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    volumeMounts:
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true

  steps:
    - name: publish-index-image
      volumeMounts:
        - name: publishing-credentials
          mountPath: /mnt/publishingCredentials
      securityContext:
        runAsUser: 1001
      image: >-
        quay.io/konflux-ci/release-service-utils@sha256:454e457cdadd5892b31fe2b7d4911b3d3a761f5705bb0cd30f864be0a597594b
      computeResources:
        limits:
          memory: 64Mi
        requests:
          memory: 64Mi
          cpu: 400m
      script: |
        #!/usr/bin/env bash
        set -euo pipefail

        SOURCE_INDEX_CREDENTIAL="$(cat /mnt/publishingCredentials/sourceIndexCredential)"
        TARGET_INDEX_CREDENTIAL="$(cat /mnt/publishingCredentials/targetIndexCredential)"

        PATH=/bin:/usr/bin:/usr/local/bin
        export PATH

        SOURCE_AUTH_ARGS=()
        if [[ ! "$(params.sourceIndex)" =~ ^registry-proxy(\-stage)?.engineering.redhat.com ]]; then
            SOURCE_AUTH_ARGS=("--src-creds" "${SOURCE_INDEX_CREDENTIAL}")
        fi

        TARGET_AUTH_ARGS=("--dest-creds" "${TARGET_INDEX_CREDENTIAL}")

        # Extract digest from pull spec
        SOURCE_INDEX="$(params.sourceIndex)"
        SOURCE_DIGEST="${SOURCE_INDEX##*@}"

        echo "Getting target image digest: $(params.targetIndex)"
        if TARGET_DIGEST=$(skopeo inspect \
            "docker://$(params.targetIndex)" \
            --format '{{.Digest}}' \
            --retry-times "$(params.retries)"); then
            echo "Target image exists."
            echo "DEBUG: Source Digest - $SOURCE_DIGEST"
            echo "DEBUG: Target Digest - $TARGET_DIGEST"
            if [ "$SOURCE_DIGEST" == "$TARGET_DIGEST" ]; then
                echo "Image already exists with the same digest, skipping copy." | tee "$(results.requestMessage.path)"
                exit 0
            else
                echo "Image exists in target registry but digests do not match." \
                    "Proceeding to copy the image."
            fi
        else
            echo "Target image does not exist. Proceeding to copy the image."
        fi

        # Proceed with copying the image
        echo "Copying image from $(params.sourceIndex) to $(params.targetIndex)"
        (skopeo copy \
        --all \
        --preserve-digests \
        --retry-times "$(params.retries)" \
        --src-tls-verify=false "${SOURCE_AUTH_ARGS[@]}" \
        "docker://$(params.sourceIndex)" \
        "${TARGET_AUTH_ARGS[@]}" \
        "docker://$(params.targetIndex)" && \
        echo -n "Index Image Published successfully" || \
        echo -n "Failed publishing Index Image" ) | tee "$(results.requestMessage.path)"

        # Ensure the script exits with the correct status
        grep "success" "$(results.requestMessage.path)" >/dev/null
