---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup-workspace
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task to delete a given directory in a passed workspace and cleanup InternalRequests related to the current
    PipelineRun.
  params:
    - name: subdirectory
      type: string
      description: The directory to remove within the workspace
    - name: delay
      type: string
      default: 60
      description: Time in seconds to delay the cleanup action
    - name: pipelineRunUid
      type: string
      default: ""
      description: The uid of the current pipelineRun. It is only available at the pipeline level
    - name: caTrustConfigMapName
      type: string
      description: The name of the ConfigMap to read CA bundle data from
      default: trusted-ca
    - name: caTrustConfigMapKey
      type: string
      description: The name of the key in the ConfigMap that contains the CA bundle data
      default: ca-bundle.crt
  workspaces:
    - name: input
      description: Workspace where the directory to cleanup exists
  volumes:
    - name: trusted-ca
      configMap:
        name: $(params.caTrustConfigMapName)
        items:
          - key: $(params.caTrustConfigMapKey)
            path: ca-bundle.crt
        optional: true
  stepTemplate:
    volumeMounts:
      - name: trusted-ca
        mountPath: /mnt/trusted-ca
        readOnly: true
  steps:
    - name: cleanup
      image: quay.io/konflux-ci/release-service-utils@sha256:f10b4ad888634a7633f76ede29003ce1471aec2b76a7d9e01ad282a3011eb78f
      computeResources:
        limits:
          memory: 64Mi
        requests:
          memory: 64Mi
          cpu: 60m
      script: |
        #!/usr/bin/env bash
        set -eux

        if [ -n "$(params.pipelineRunUid)" ] ; then
            # Cleanup all internalrequests, but only if internalrequests exist on cluster
            if kubectl api-resources | grep InternalRequest | grep appstudio.redhat.com ; then
              kubectl delete internalrequest \
                  -l internal-services.appstudio.openshift.io/pipelinerun-uid="$(params.pipelineRunUid)"
            else
              echo "CRD internalrequests.appstudio.redhat.com not found on cluster"
            fi
        fi

        if [ -z "$(params.subdirectory)" ] ; then
            echo "The empty string is not a valid subdirectory"
            exit 0
        fi

        echo "Delaying execution by $(params.delay) seconds"
        sleep "$(params.delay)"

        CLEANUP_DIR="$(workspaces.input.path)/$(params.subdirectory)"

        if [ -d "${CLEANUP_DIR}" ] ; then
          # Delete a directory and its contents
          rm -rf "${CLEANUP_DIR}"
        fi
