---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: prepare-validation
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task to extract a pull spec from a Snapshot.
    
    The purpose of this task is to extract just a single component's pullSpec from a passed Snapshot.
  params:
    - name: snapshot
      type: string
      description: The Snapshot in JSON format to apply the mapping to
  results:
    - name: snapshot
      type: string
      description: |
        The pullSpec of the first component in the passed Snapshot.
  steps:
    - name: prepare-validation
      image:
        quay.io/konflux-ci/release-service-utils:02a8ddcd16113371a255fd1ef0a196399d300162
      computeResources:
        limits:
          memory: 128Mi
        requests:
          memory: 128Mi
          cpu: 50m
      script: |
        #!/usr/bin/env bash
        set -eux

        jq -jr '.components[0].containerImage' <<< '$(params.snapshot)' \
          | tee "$(results.snapshot.path)"
