---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup-internal-requests
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Tekton task to delete internal requests associated with a pipelinerun
  params:
    - name: pipelineRunUid
      type: string
      description: The uid of the current pipelineRun. It is only available at the pipeline level
  steps:
    - name: cleanup-internal-requests
      image: quay.io/konflux-ci/release-service-utils:02a8ddcd16113371a255fd1ef0a196399d300162
      computeResources:
        limits:
          memory: 128Mi
        requests:
          memory: 128Mi
          cpu: 200m
      script: |
        #!/usr/bin/env bash
        set -eux

        if [ -n "$(params.pipelineRunUid)" ] ; then
            # Cleanup all internalrequests, but only if internalrequests exist on cluster
            if kubectl api-resources | grep InternalRequest | grep appstudio.redhat.com ; then
              kubectl delete internalrequest \
                  -l internal-services.appstudio.openshift.io/pipelinerun-uid="$(params.pipelineRunUid)"
            else
              echo "CRD internalrequests.appstudio.redhat.com not found on cluster"
            fi
        fi
